### ISSUE TITLE
pvlib warning upon set1axis -- tracking on surface azimuth

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#255] opened 2020-05-26 21:33 UTC
![image](https://user-images.githubusercontent.com/22824806/82952397-21c10580-9f66-11ea-83a3-394aaa4ba3a2.png)

**Comment by cdeline** [comment] 2020-05-29 20:03
#260 is a duplicate of this.  It was fixed by https://github.com/NREL/bifacial_radiance/commit/3b44160f7b6d2f4d89b7c7bf30af9b3facca5b2c which is merged into master.

**Closed by cdeline** 2020-05-29 20:03 UTC
